name: publicacao

on:
  push:
    paths:
      - index.md
      - schema.yaml

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install livemark
        run: pip install -r requirements.txt
      - name: Build Livemark
        run: make build
      - name: Commit new datapackage.json
        uses: stefanzweifel/git-auto-commit-action@v4 